trigger:
  branches:
    include:
    - pre
    - main
  paths:
    include:
    - fabric/**

parameters:
- name: items_in_scope
  displayName: Enter Fabric items to be deployed
  type: string
  default: '["Lakehouse","VariableLibrary","Notebook","DataPipeline","SemanticModel","Report"]'

variables:
  - group: fabric_cicd_group_sensitive
  - group: fabric_cicd_group_non_sensitive
  - name: target_env
    value: ${{ variables['Build.SourceBranchName'] }}

stages:
  - stage: DeployPre
    displayName: "Deploy to PRE"
    condition: eq(variables['Build.SourceBranchName'], 'pre')
    jobs:
      - deployment: Deployment
        displayName: "Deploy Resources to PRE"
        environment: pre
        pool:
          name: Azure Pipelines
        strategy:
          runOnce:
            deploy:
              steps:
                # Step 1: Checkout the source code
                - checkout: self
                # Step 2: Set up Python 3.12
                - task: UsePythonVersion@0
                  inputs:
                    versionSpec: '3.12'
                    addToPath: true
                  displayName: "Set up Python Environment"
                # Step 3: Install dependencies
                - script: |
                    python -m pip install --upgrade pip
                    pip install fabric-cicd 
                  displayName: "Install Fabric CICD Library"
                # Step 4: Run the deployment script
                - task: PythonScript@0
                  inputs:
                    scriptSource: filePath
                    scriptPath: '.deploy/deploy-to-fabric.py'
                    arguments: >-
                      --aztenantid $(pre-aztenantid)
                      --azclientid $(pre-azclientid)
                      --azspsecret $(pre-azspsecret)
                      --items_in_scope "${{ parameters.items_in_scope }}"
                      --target_env pre
                  displayName: 'Deploy via fabric-cicd'

  - stage: DeployMain
    displayName: "Deploy to PRO"
    condition: eq(variables['Build.SourceBranchName'], 'main')
    jobs:
      - deployment: Deployment
        displayName: "Deploy Resources to PRO"
        environment: main
        pool:
          name: Azure Pipelines
        strategy:
          runOnce:
            deploy:
              steps:
                # Step 1: Checkout the source code
                - checkout: self
                # Step 2: Set up Python 3.12
                - task: UsePythonVersion@0
                  inputs:
                    versionSpec: '3.12'
                    addToPath: true
                  displayName: "Set up Python Environment"
                # Step 3: Install dependencies
                - script: |
                    python -m pip install --upgrade pip
                    pip install fabric-cicd 
                  displayName: "Install Fabric CICD Library"
                # Step 4: Run the deployment script
                - task: PythonScript@0
                  inputs:
                    scriptSource: filePath
                    scriptPath: '.deploy/deploy-to-fabric.py'
                    arguments: >-
                      --aztenantid $(pro-aztenantid)
                      --azclientid $(pro-azclientid)
                      --azspsecret $(pro-azspsecret)
                      --items_in_scope "${{ parameters.items_in_scope }}"
                      --target_env main
                  displayName: 'Deploy via fabric-cicd'